### PR TITLE
Use only golang/dep and remove other glide/godep files

### PR DESCRIPTION
**Pull request by vdemeester**
This also cleans some code because of the `prune` options of `golang/dep`

… also had to use `moby/buildkit` parser instead of docker as the
docker/docker dependency that `go-dockerclient` has is now using this
package for the parsing.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@smarterclayton @nalind @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
#94 has been merged, @vdemeester can you rebase and update as needed please?

**Comment by vdemeester** [comment]
> … also had to use `moby/buildkit` parser instead of docker as the
> docker/docker dependency that `go-dockerclient` has is now using this
> package for the parsing.

**Comment by vdemeester** [comment]
Arf… So… I think the `docker/docker` version `go-dockerclient` depends doesn't compile on Go 1.9 anymore… I'll revert the bump for moby as I'm not sure if Go 1.9 support can be dropped or not… I'll do a follow-up :wink: 

```
# github.com/openshift/imagebuilder/vendor/github.com/docker/docker/pkg/archive
vendor/github.com/docker/docker/pkg/archive/archive.go:365:5: hdr.Format undefined (type *tar.Header has no field or method Format)
vendor/github.com/docker/docker/pkg/archive/archive.go:365:15: undefined: tar.FormatPAX
vendor/github.com/docker/docker/pkg/archive/archive.go:1167:7: hdr.Format undefined (type *tar.Header has no field or method Format)
vendor/github.com/docker/docker/pkg/archive/archive.go:1167:17: undefined: tar.FormatPAX
```

**Comment by rhatdan** [comment]
I would think we can drop it.  We usually support go version -1 and later.

**Comment by vdemeester** [comment]
@rhatdan ok, I'll prepare an update in a separate PR then :wink:

**Comment by smarterclayton** [comment]
We can drop go 1.9 support

**Comment by TomSweeneyRedHat** [comment]
LGTM, @rhatdan , @bparees and/or @smarterclayton any objections to merging.
