### ISSUE TITLE
`go get` fails

### ISSUE THREAD

**Issue by maxamillion** [openshift/imagebuilder#5]
```
$ go get -u github.com/openshift/imagebuilder/cmd/imagebuilder
# github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/filters
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/filters/parse.go:12:45: error: import file ‘github.com/docker/engine-api/types/versions’ not found
  "github.com/docker/engine-api/types/versions"
                                             ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/filters/parse.go:84:22: error: reference to undefined name ‘versions’
  if version != "" && versions.LessThan(version, "1.22") {
                      ^
# github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/config.go:4:45: error: import file ‘github.com/docker/engine-api/types/strslice’ not found
  "github.com/docker/engine-api/types/strslice"
                                             ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/config.go:5:38: error: import file ‘github.com/docker/go-connections/nat’ not found
  "github.com/docker/go-connections/nat"
                                      ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/config.go:21:25: error: expected package
  ExposedPorts    map[nat.Port]struct{} `json:",omitempty"` // List of exposed ports
                         ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/config.go:26:26: error: expected package
  Cmd             strslice.StrSlice     // Command to run when starting the container
                          ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/config.go:31:26: error: expected package
  Entrypoint      strslice.StrSlice     // Entrypoint to run when starting the container
                          ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:6:45: error: import file ‘github.com/docker/engine-api/types/blkiodev’ not found
  "github.com/docker/engine-api/types/blkiodev"
                                             ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:7:45: error: import file ‘github.com/docker/engine-api/types/strslice’ not found
  "github.com/docker/engine-api/types/strslice"
                                             ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:8:38: error: import file ‘github.com/docker/go-connections/nat’ not found
  "github.com/docker/go-connections/nat"
                                      ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:9:28: error: import file ‘github.com/docker/go-units’ not found
  "github.com/docker/go-units"
                            ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:221:34: error: expected package
  BlkioWeightDevice    []*blkiodev.WeightDevice
                                  ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:222:34: error: expected package
  BlkioDeviceReadBps   []*blkiodev.ThrottleDevice
                                  ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:223:34: error: expected package
  BlkioDeviceWriteBps  []*blkiodev.ThrottleDevice
                                  ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:224:34: error: expected package
  BlkioDeviceReadIOps  []*blkiodev.ThrottleDevice
                                  ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:225:34: error: expected package
  BlkioDeviceWriteIOps []*blkiodev.ThrottleDevice
                                  ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:238:31: error: expected package
  Ulimits              []*units.Ulimit // List of ulimits to be set in the container
                               ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:265:21: error: expected package
  PortBindings    nat.PortMap   // Port mapping between the exposed port (container) and the host
                     ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:272:26: error: expected package
  CapAdd          strslice.StrSlice // List of kernel capabilities to add to the container
                          ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/engine-api/types/container/host_config.go:273:26: error: expected package
  CapDrop         strslice.StrSlice // List of kernel capabilities to remove from the container
                          ^
# github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/system
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/system/meminfo_linux.go:10:71: error: import file ‘github.com/fsouza/go-dockerclient/external/github.com/docker/go-units’ not found
  "github.com/fsouza/go-dockerclient/external/github.com/docker/go-units"
                                                                       ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/system/meminfo_linux.go:45:26: error: reference to undefined name ‘units’
   bytes := int64(size) * units.KiB
                          ^
# github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/ioutils
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/ioutils/readers.go:8:69: error: import file ‘github.com/fsouza/go-dockerclient/external/golang.org/x/net/context’ not found
  "github.com/fsouza/go-dockerclient/external/golang.org/x/net/context"
                                                                     ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/ioutils/readers.go:98:37: error: expected package
 func NewCancelReadCloser(ctx context.Context, in io.ReadCloser) io.ReadCloser {
                                     ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/ioutils/readers.go:102:21: error: reference to undefined name ‘context’
  doneCtx, cancel := context.WithCancel(context.Background())
                     ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/ioutils/readers.go:102:40: error: reference to undefined name ‘context’
  doneCtx, cancel := context.WithCancel(context.Background())
                                        ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/ioutils/readers.go:113:13: error: expected channel
   case <-ctx.Done():
             ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/ioutils/readers.go:125:14: error: expected channel
    case <-ctx.Done():
              ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/ioutils/readers.go:127:18: error: expected channel
    case <-doneCtx.Done():
                  ^
# github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:11:42: error: import file ‘github.com/docker/docker/builder/command’ not found
  "github.com/docker/docker/builder/command"
                                          ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:50:3: error: reference to undefined name ‘command’
   command.User:       parseString,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:51:3: error: reference to undefined name ‘command’
   command.Onbuild:    parseSubCommand,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:52:3: error: reference to undefined name ‘command’
   command.Workdir:    parseString,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:53:3: error: reference to undefined name ‘command’
   command.Env:        parseEnv,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:54:3: error: reference to undefined name ‘command’
   command.Label:      parseLabel,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:55:3: error: reference to undefined name ‘command’
   command.Maintainer: parseString,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:56:3: error: reference to undefined name ‘command’
   command.From:       parseString,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:57:3: error: reference to undefined name ‘command’
   command.Add:        parseMaybeJSONToList,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:58:3: error: reference to undefined name ‘command’
   command.Copy:       parseMaybeJSONToList,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:59:3: error: reference to undefined name ‘command’
   command.Run:        parseMaybeJSON,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:60:3: error: reference to undefined name ‘command’
   command.Cmd:        parseMaybeJSON,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:61:3: error: reference to undefined name ‘command’
   command.Entrypoint: parseMaybeJSON,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:62:3: error: reference to undefined name ‘command’
   command.Expose:     parseStringsWhitespaceDelimited,
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/docker/docker/builder/parser/parser.go:63:3: error: reference to undefined name ‘command’
   command.Volume:     parseMaybeJSONToList,
   ^
# github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/fileutils
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/fileutils/fileutils.go:13:71: error: import file ‘github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus’ not found
  "github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus"
                                                                       ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/fileutils/fileutils_unix.go:10:71: error: import file ‘github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus’ not found
  "github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus"
                                                                       ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/fileutils/fileutils.go:116:3: error: reference to undefined name ‘logrus’
   logrus.Debugf("Skipping excluded path: %s", file)
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/fileutils/fileutils_unix.go:17:3: error: reference to undefined name ‘logrus’
   logrus.Errorf("Error opening /proc/%d/fd: %s", os.Getpid(), err)
   ^
# github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:8:71: error: import file ‘github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus’ not found
  "github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus"
                                                                       ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:101:6: error: reference to undefined name ‘logrus’
      logrus.Debugf("Corrupted prefix: %v", buf[:nr])
      ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:107:5: error: reference to undefined name ‘logrus’
     logrus.Debugf("Error reading header: %s", er)
     ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:123:4: error: reference to undefined name ‘logrus’
    logrus.Debugf("Error selecting output fd: (%d)", buf[stdWriterFdIndex])
    ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:129:3: error: reference to undefined name ‘logrus’
   logrus.Debugf("framesize: %d", frameSize)
   ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:134:4: error: reference to undefined name ‘logrus’
    logrus.Debugf("Extending buffer cap by %d (was %d)", frameSize+stdWriterPrefixLen-bufLen+1, len(buf))
    ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:146:6: error: reference to undefined name ‘logrus’
      logrus.Debugf("Corrupted frame: %v", buf[stdWriterPrefixLen:nr])
      ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:152:5: error: reference to undefined name ‘logrus’
     logrus.Debugf("Error reading frame: %s", er)
     ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:160:4: error: reference to undefined name ‘logrus’
    logrus.Debugf("Error writing frame: %s", ew)
    ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy/stdcopy.go:165:4: error: reference to undefined name ‘logrus’
    logrus.Debugf("Error Short Write: (%d on %d)", nw, frameSize)
    ^
# github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/homedir
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/homedir/homedir.go:7:93: error: import file ‘github.com/fsouza/go-dockerclient/external/github.com/opencontainers/runc/libcontainer/user’ not found
  "github.com/fsouza/go-dockerclient/external/github.com/opencontainers/runc/libcontainer/user"
                                                                                             ^
../../../go/src/github.com/openshift/imagebuilder/vendor/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/homedir/homedir.go:25:16: error: reference to undefined name ‘user’
   if u, err := user.CurrentUser(); err == nil {
                ^
```

**Comment by smarterclayton** [comment]
Works for me.  Are you on Go 1.6 or above?

**Comment by smarterclayton** [comment]
Closing as this works on Go 1.6

**Comment by maxamillion** [comment]
Fails with golang-1.6.3-1.fc24.x86_64 on Fedora 24, but that's fine.

**Comment by smarterclayton** [comment]
Can you report the value of GOVENDOREXPERIMENT= in your environment?  I have been unable to reproduce this in clean GOPATHs - my concern may be that this is a problem with Fedora 24.

**Comment by smarterclayton** [comment]
```
[vm]$ mkdir /tmp/t1
[vm]$ pushd /tmp/t1
/tmp/t1 /data/src/github.com/openshift/origin
[vm]$ export GOPATH^C
[vm]$ GOPATH=$(pwd) go get -u github.com/openshift/imagebuilder
[vm]$ go version
go version go1.6.3 linux/amd64
[vm]$ dnf info golang
Last metadata expiration check: 9 days, 9:20:48 ago on Sun Aug  7 19:44:46 2016.
Installed Packages
Name        : golang
Arch        : x86_64
Epoch       : 0
Version     : 1.6.3
Release     : 1.fc24
Size        : 11 M
Repo        : @System
From repo   : @commandline
Summary     : The Go Programming Language
URL         : http://golang.org/
License     : BSD and Public Domain
Description : The Go Programming Language.
```

**Comment by smarterclayton** [comment]
Is there anything special about your GOPATH?  SELinux labels out of joint?  Directories owned by root?

**Comment by maxamillion** [comment]
*sigh* .... `go` is set to gccgo by default it would appear.

So that's fun.

```
$ go version
go version go1.6.1 gccgo (GCC) 6.1.1 20160621 (Red Hat 6.1.1-3) linux/amd64
```

**Comment by smarterclayton** [comment]
:)

**Comment by maxamillion** [comment]
Thanks, sorry for the line noise :)
